// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMMdM03nAuP6fHiVz9YFhj6O9Mm6nvShg',
    appId: '1:456729626492:web:4863f35ac209f0eaad06f9',
    messagingSenderId: '456729626492',
    projectId: 'excellent-camp-223911',
    authDomain: 'excellent-camp-223911.firebaseapp.com',
    storageBucket: 'excellent-camp-223911.appspot.com',
    measurementId: 'G-07QNYR0EC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjcUMBAAVGun_A7ce9R-5MaZLtsWh1_Z0',
    appId: '1:456729626492:android:97d6acc00d1fa7ecad06f9',
    messagingSenderId: '456729626492',
    projectId: 'excellent-camp-223911',
    storageBucket: 'excellent-camp-223911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyNEyCJRDjXaySzqyfaojHa7BdVvRhw8',
    appId: '1:456729626492:ios:86dbe043b0503ba8ad06f9',
    messagingSenderId: '456729626492',
    projectId: 'excellent-camp-223911',
    storageBucket: 'excellent-camp-223911.appspot.com',
    iosBundleId: 'com.example.myRealConvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyNEyCJRDjXaySzqyfaojHa7BdVvRhw8',
    appId: '1:456729626492:ios:96bcf510f1fb9c94ad06f9',
    messagingSenderId: '456729626492',
    projectId: 'excellent-camp-223911',
    storageBucket: 'excellent-camp-223911.appspot.com',
    iosBundleId: 'com.example.myRealConvApp.RunnerTests',
  );
}
